#!/usr/bin/env python3
# Copyright (c) 2020 Stuart McGraw
# SPDX-License-Identifier: GPL-2.0-or-later

# This web page will show some details about the CGI/Python execution
# environment and is useful for diagnosing library location confusions.

# WARNING: The page generated by this view will show all items from the
# config.ini files, including those in the config-pvt.ini file (other
# than the db_* sections what are optionally supressed).

# NOTE: this view returns raw HTML rather than data to be rendered
# via a Jinja template.
# Note that unlike CGI scripts which read the jmdictdb config file on
# every html request, the jmapp script reads the config file only once
# when the webserver starts its Python subinterpreter and that configuration
# is used for all following html requests including this one.
# A restart of the Python subinterpreter can be requested without a full
# webserver restart by 'touch'ing the jmapp.wsgi file.

import sys, configparser, html, os, pdb
try: import pkgpath.py  # Make jmdictdb package available on sys.path.
except ImportError: pass

def main():
        try: import jmdictdb
        except ImportError:
            content = """\
                <h3>Failed to import jmdictdb</h3>
                Current directory is: %s<br>
                sys.path is: %r"""  % (os.getcwd(), sys.path)
            return Page % content
        from jmdictdb import jdb, config, jmcgi

        row_tmpl = "    <tr><td>%s</td><td>%s</td></tr>"

  # NOTE: Be mindful of the distinction between cfg.get()
  # and cfg_get() below.

        exdata = []
        exdata.append (('cwd', os.getcwd()))
        exdata.append (('cgi location',
                     os.path.dirname (os.path.abspath (__file__))))
        exdata.append (('pkg location',
                     os.path.dirname (os.path.abspath (jdb.__file__))))
        exdata.append (('sys.path', '%r' % sys.path))
        ex_rows = '\n'.join ([row_tmpl % (key.replace(' ','&nbsp;'), html.escape(value))
                              for key,value in exdata])

        cfgdata = []
          # The canonical definition the CGI config file location is
          # defined by the variable CONFIG_FILE in module jmcgi.
        try: cfg = config.cfgRead (jmcgi.CONFIG_FILE)
        except Exception as e:
            cfgdata.append ((jmcgi.CONFIG_FILE, str(e)))
        else:
            cfgdata.append (('config dir', cfg.get ('status', 'cfg_dir')))
            cfgdata.append (('config files',
                            cfg.get ('status', 'cfg_files')))
            cfgdata.append (cfg_get (cfg, 'logging', 'LOG_FILENAME'))
            cfgdata.append (cfg_get (cfg, 'web', 'STATUS_DIR'))
            cfgdata.extend (cfg_svcs (cfg))
        cfg_rows = '\n'.join ([row_tmpl % (key.replace(' ','&nbsp;'),
                                           html.escape(value).replace("\n","<br>"))
                              for key,value in cfgdata])

        env_rows = '\n'.join ([row_tmpl % (key.replace(' ','&nbsp;'), html.escape(value))
                              for key,value in sorted (os.environ.items())])

        htmltxt = Page % (ex_rows, cfg_rows, env_rows)
        print ("Content-type: text/html\n\n", htmltxt)

def cfg_get (cfg, section, key):
        tag = "[%s] %s" % (section, key)
        try: value = cfg.get (section, key)
        except (configparser.NoSectionError, configparser.NoOptionError) as e:
            return tag, str(e)
        return tag, value

def cfg_svcs (cfg):
        results = [];  warns = []
        default_svc = cfg.get ('web', 'DEFAULT_SVC')
        results.append (('[web] DEFAULT_SVC', default_svc))
        svcs = [x[3:] for x in cfg.sections() if x.startswith ('db_')]
          # Report if 'db_session is missing but don't explicitly report
          # its presence.
        if 'session' in svcs: svcs.remove ('session')
        else: warns.append (('WARNING', "'session' not in svc's"))
        if default_svc not in svcs:
            warns.append (('WARNING', "default svc not in svc's"))
        results.append (("services", (', '.join(svcs))))
        return results + warns

  # Don't forget to double "%" characters below.
Page = '''<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>JMdictDB - Configuration details</title>
  <style>
    body         {font-family: arial;}
    .item        {background: #E8FFF0;
                 border-style: solid; border-width: thin;
                 margin: 5px; padding: 10px}
    .notes      {font-size: 75%%;}
    .err {color:red;} td {vertical-align: top;} .pre {white-space: pre;}
    </style>
  </head>
<body>
  <p>Execution info:
  <table class="item">
    %s
    </table>
  <p>Config info:<br>
  <table class="item">
    %s
    </table>
    <span class="notes">Note: No <b>LOG_FILENAME</b> value means log
      output to stderr.</span>
  <p>Environment info:<br>
  <table class="item">
    %s
    </table>
'''
main()
